name: Daily Perplexity Update

on:
  schedule:
    - cron: "*/5 * * * *"   # Runs every 5 minutes (minimum GitHub-supported interval)
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  run-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests

      - name: Generate auto-prompt + single-file app
        env:
          PPLX_API_KEY: ${{ secrets.PPLX_API_KEY }}
        run: python automation/generate.py

      - name: Commit & push if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "automation using Perplexity AI"
          commit_user_name: "rahimbaig28"
          commit_user_email: "rahimbaig00332211@gmail.com"
          file_pattern: |
            dist/app.html
            dist/prompt.txt
