name: Daily Perplexity Update

on:
  schedule:
    - cron: "0 13 * * *"   # run once daily at 13:00 UTC
  workflow_dispatch: {}

# prevent overlapping runs
concurrency:
  group: perplexity-auto
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  run-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests

      # Retries the generator up to 3 times and gives the API more time to respond
      - name: Generate auto-prompt + single-file app (with retries)
        env:
          PPLX_API_KEY: ${{ secrets.PPLX_API_KEY }}
          PPLX_TIMEOUT: "420"        # read-timeout seconds; tune if needed
          PPLX_MODEL: "sonar"        # override model if desired
        run: |
          set -e
          for i in 1 2 3; do
            echo "Attempt $i..."
            if python automation/generate.py; then
              echo "Success."
              break
            fi
            echo "Attempt $i failed. Sleeping before retry..."
            sleep 10
          done

      - name: Show generated files
        run: |
          echo "== dist tree =="
          ls -lah dist || true
          echo "== prompts =="
          ls -lah dist/prompts || true
          echo "== apps =="
          ls -lah dist/apps || true
          echo "== latest =="
          ls -lah dist/latest || true

      - name: Verify prompt exists
        run: |
          test -f dist/latest/prompt.txt || (echo "No prompt found at dist/latest/prompt.txt" && exit 1)

      - name: Commit & push if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "automation using Perplexity AI"
          commit_user_name: "rahimbaig28"
          commit_user_email: "rahimbaig00332211@gmail.com"
          file_pattern: "dist/**"
          add_options: "--force"   # commits even if dist/ is ignored by .gitignore
